<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

	<!--This automatically copies ALL json files within the solution into our output directory-->
	<ItemGroup>
		<MySourceFiles Include="$(SolutionDir)*\*.json" />
	</ItemGroup>

	<Target Name="CopyConfigurationFiles" AfterTargets="Build">
		<Copy SourceFiles="@(MySourceFiles)" DestinationFolder="$(OutDir)" />
	</Target>			
	<!--END CONFIGURATION COPY SECTION-->
	
	<!--#if (UseTranslations) -->
	<ItemGroup>
		<TranslationFiles Include="$(SolutionDir)*\translations\*.json" />
	</ItemGroup>

	<Target Name="CopyTranslationFiles" AfterTargets="Build">
		<Copy SourceFiles="@(TranslationFiles)" DestinationFolder="$(OutDir)\translations" />
	</Target>
	<!--#endif-->
	
  <ItemGroup>
    <PackageReference Include="DisCatSharp.Hosting.AspNetCore" Version="10.7.1-nightly-027" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

	<!--#if (IncludeBot) -->
	<ItemGroup>
		<ProjectReference Include="..\DisCatSharpProjectBot\DisCatSharpProject.Bot.csproj" />
	</ItemGroup>

	<!--#endif -->

</Project>
